name: Deploy Production

on:
  push:
    branches:
      - main

# IMPORTANT:
# - Add .nojekyll file in output folder to inform GitHub not to build the project using Jekyll.
# - Using GitHub Pages without a custom domain will result in deployed site breaking, as static assets and URLs are not linked properly.
# For more information, check out https://dev.to/jameswallis/deploying-a-next-js-app-to-github-pages-24pn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn
          yarn build
          touch out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: out
